# Copyright (C) 2017 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved
# This file is available under the MIT license.

sudo: required

language: c

services:
- docker

script:
- docker build --tag quay.io/kkohtaka/cratedb-prometheus-adapter .

after_success:
- |
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login --username="$docker_username" --password="$docker_password";
    docker push quay.io/kkohtaka/cratedb-prometheus-adapter;
  fi
