# Copyright (C) 2017 Kazumasa Kohtaka <kkohtaka@gmail.com> All right reserved
# This file is available under the MIT license.

sudo: required

language: c

addons:
  apt:
    packages:
    - docker-ce

services:
- docker

script:
- docker build --tag quay.io/kkohtaka/cratedb-prometheus-adapter .
- |
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login --username="$docker_username" --password="$docker_password" quay.io;
    docker push quay.io/kkohtaka/cratedb-prometheus-adapter;
  fi
